thiet ke trang/Areas/Admin/Controllers/Products1Controller.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using thiet_ke_trang.Models;
using thiet_ke_trang.Models.ViewModel;
namespace thiet_ke_trang.Areas.Admin.Controllers
{
    public class Products1Controller : Controller
    {
        private MyStoreEntities db = new MyStoreEntities();

        // GET: Admin/Products1
        public ActionResult Index(string searchTerm,decimal?Minprice,decimal?Maxprice,string SortOrder,int?page )
        {
            var model = new ProductSearchVM();
            var products = db.Products.AsQueryable();
            if (!string.IsNullOrEmpty(searchTerm))
            {
                model.SearchTerm= searchTerm;
                products = products.Where(p =>
                    p.ProductName.Contains(searchTerm)||
                    p.ProductDecription.Contains(searchTerm)||
                    p.Category.CategoryName.Contains(searchTerm));
            }
            if (Minprice.HasValue)
            {
                model.Minprice = Minprice.Value;
                products = products.Where(p => p.ProductPrice >= Minprice.Value);
            }
            if (Maxprice.HasValue)
            {
                model.Maxprice = Maxprice.Value;
                products = products.Where(p => p.ProductPrice <= Minprice.Value);
            }
            switch (SortOrder)
            {
                case "name_asc": products.OrderBy(p => p.ProductName);
                    break;
                case "name_desc":products.OrderByDescending(p => p.ProductName);
                    break;
                case "price_asc": products.OrderBy(p=>p.ProductPrice);
                    break;
                case "price_desc": products.OrderByDescending(p=>p.ProductPrice);
                    break;
                default:
                    products = products.OrderBy(p => p.ProductName);
                    break;
            }
            model.SortOrder = SortOrder;
            int pageNumber = page ?? 1;
            int pagesize = 2;
                //model.Products = products.ToList();
            return View(model);
        }

        // GET: Admin/Products1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Admin/Products1/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Admin/Products1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,CategoryID,ProductName,ProductDecription,ProductPrice,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // POST: Admin/Products1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,CategoryID,ProductName,ProductDecription,ProductPrice,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/Products1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

thiet ke trang/Areas/Admin/Views/Products1/Create.cshtml
@model thiet_ke_trang.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2 class="bg-info">THÊM SẢN PHẨM</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("PCVCreateEditProducts1",Model)
    </div>
}

thiet ke trang/Areas/Admin/Views/Products1/Delete.cshtml
@model thiet_ke_trang.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<head>
    <style>
        
    </style>
</head>
<h2 class="btn btn-info">XÓA SẢN PHẨM</h2>
<h3 class="bg-warning">Bạn chắc chắn muốn xóa sản phẩm này à?</h3>
@Html.Partial("PVCDetailProductIndex", Model)
<div class="form-group">
    <div style="float:right"class="col-md-offset-3 col-md-9">
    @Html.ActionLink("Xóa", "Delete", new { id = Model.ProductID }, new { @class = "btn btn-primary btn-sm" }) |
    @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

thiet ke trang/Areas/Admin/Views/Products1/Details.cshtml
@model thiet_ke_trang.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2 class="btn btn-info">CHI TIẾT SẢN PHẨM</h2>
@Html.Partial("PVCDetailProductIndex",Model)
<div class="form-group">
    <div style="float:right" class="col-md-offset-3 col-md-9">
            @Html.ActionLink("Cập nhật", "Edit", new { id = Model.ProductID }, new { @class = "btn btn-primary btn-sm" }) |
            @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

thiet ke trang/Areas/Admin/Views/Products1/Edit.cshtml
@model thiet_ke_trang.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>CẬP NHẬT SẢN PHẨM</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProductID)
    @Html.Partial("PCVCreateEditProducts1", Model)
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

thiet ke trang/Areas/Admin/Views/Products1/Index.cshtml
@model thiet_ke_trang.Models.ViewModel.ProductSearchVM

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
    <style>
        .search-container,.order-container{
            padding-top:20px;
            display:flex;
            justify-content:center;
            align-items:center;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Index", "Products1", FormMethod.Get))
    {
                <div class="form-group search-container">
                    @Html.TextBoxFor(m => m.SearchTerm, new
                   {
                     @class = "form-control",
                     placeholder = "Nhập tên, mô tả hoặc loại sản phẩm"
                   })
                    @Html.TextBoxFor(m => m.Minprice, new
               {
                 @class = "form-control",
                 placeholder = "Nhập giá tối thiểu",
                 type="Number"
               })
                    @Html.TextBoxFor(m => m.Maxprice, new
               {
                 @class = "form-control",
                 placeholder = "Nhập giá tối đa",
                 type="Number"
               })
                    <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                </div>
                <div class="form-group order-container">
                    Sắp xếp theo:
                    @Html.ActionLink("Tên tăng dần", "Index", "Products1", new
               {
                   SortOrder = "name_asc",
                   searchTerm = Model.SearchTerm,
                   Minpice = Model.Minprice,
                   Maxprice = Model.Maxprice
               }, null)|
                    @Html.ActionLink("Tên giảm dần", "Index", "Products1", new
                   {
                       SortOrder = "name_asc",
                       SearchTerm = Model.SearchTerm,
                       Minpice = Model.Maxprice,
                       Maxprice = Model.Minprice
                   }, null)|

                    @Html.ActionLink("Giá tăng dần", "Index", "Products1", new
                  {
                      SortOrder = "price_asc",
                      SearchTerm = Model.SearchTerm,
                      Minpice = Model.Maxprice,
                      Maxprice = Model.Minprice
                  }, null)|
                    @Html.ActionLink("Giá giảm dần", "Index", "Products1", new
                  {
                      SortOrder = "price_asc",
                      SearchTerm = Model.SearchTerm,
                      Minpice = Model.Maxprice,
                      Maxprice = Model.Minprice
                  }, null)|
                </div>
    }
    @Html.Partial("PCVListProducts1",Model)
</body>
</html>

thiet ke trang/Areas/Admin/Views/Products1/PCVCreateEditProducts1.cshtml
@model thiet_ke_trang.Models.Product
    <style>
        textarea{
            width:100%;
            height:150%;
            padding:12px 5px;
            box-sizing:border-box;
            border:1px solid #000000;
            border-radius:5px;
            background-color:whitesmoke;
            resize:none;
        }
    </style>
<div class="form-group">
    <div class="control-label col-md-2">Danh mục</div>
    <div class="col-md-10">
        @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="control-label col-md-2">Tên sản phẩm</div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="control-label col-md-2">Mô tả</div>
    <div class="col-md-10">
        @Html.TextAreaFor(model => model.ProductDecription, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ProductDecription, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="control-label col-md-2">Đơn giá</div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="control-label col-md-2">Hình ảnh</div>
    <div class="col-md-10">
        @Html.EditorFor(model => model.ProductImage, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Lưu" class="btn btn-primary btn-sm" />
        @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-primary btn-sm" })

    </div>
</div>

thiet ke trang/Areas/Admin/Views/Products1/PCVListProducts1.cshtml
@model thiet_ke_trang.Models.ViewModel.ProductSearchVM
@using PagedList.Mvc
<head>
    <style>
        img {
            height: 150px;
            width: 150px;
        }
    </style>
</head>
@if (Model.Products != null && Model.Products.Any())
{
<h2 class="bg-info">DANH SÁCH SẢN PHẨM</h2>

<table class="table bg-light col-md-6">
    <tr>
        <th class="col-md-2">Hình ảnh</th>
        <th class="col-md-2">Tên sản phẩm</th>

        <th class="col-md-2">Đơn giá</th>
        <th class="col-md-2">Danh mục</th>
        <th class="col-md-4"></th>
    </tr>
    @foreach (var product in Model.Products)
    {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => product.ProductImage)"
            </td>
            <td>
                @Html.DisplayFor(modelItem => product.ProductName)
            </td>


            <td>
                @Html.DisplayFor(modelItem => product.ProductPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => product.Category.CategoryName)
            </td>
            <td>
                @Html.ActionLink("Cập nhật", "Edit", new { id = product.ProductID }, new { @class = "btn btn-primary btn-sm" }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = product.ProductID }, new { @class = "btn btn-primary btn-sm" }) |
                @Html.ActionLink("Xóa", "Delete", new { id = product.ProductID }, new { @class = "btn btn-primary btn-sm" })
            </td>
        </tr>
    }
</table>
<div class="pagination-container">
    @Html.PagedListPager(Model.Products, page => Url.Action("Index", new { page, searchTerm = Model.SearchTerm, Minprice = Model.Minprice, Maxprice = Model.Maxprice, SortOrder = Model.SortOrder }))
</div>
}
else
            {
                <p>Không tìm thấy sản phẩm phù hợp</p>
            }
<div class="form-group">
    <div style="float:right" class="col-md-offset-4 col-md-3">
        @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

thiet ke trang/Areas/Admin/Views/Products1/PVCDetailProductIndex.cshtml
@model thiet_ke_trang.Models.Product
<head>
    <style>
        img {
            height: 250px;
            width: 250px;
        }
        
    </style>
</head>
<div class="container-fluid">
    <div class="d-flex div-horizontal">
        <div class="col-md-3">
            <img src="@Html.DisplayFor(model => model.ProductImage)" />
        </div>
        <div class="col-md-9">
            <dl>
                <dt> Tên sản phẩm: </dt>
                <dd> @Html.DisplayFor(model => model.ProductName)</dd>

                <dt>Mô tả: </dt>
                <dd>@Html.DisplayFor(model => model.ProductDecription)</dd>

                <dt>Đơn giá: </dt>
                <dd>@Html.DisplayFor(model => model.ProductPrice)</dd>
                <dt>Danh mục: </dt>
                <dd>@Html.DisplayFor(model => model.Category.CategoryName)</dd>

            </dl>
        </div>

    </div>

</div>